WebApp/Controllers/CaptureController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CaptureController : Controller
    {
        private OfficeHoursContext db = new OfficeHoursContext();
        // GET: Capture
        
        public ActionResult Index()
        {
            var facultyMail = Session["facultyMail"].ToString();
            List<CaptureNoteModel> captureNoteModels = new List<CaptureNoteModel>();

            var captureNotes = db.captureNotes
                .Where(o => o.Email.Equals(facultyMail))
                .OrderBy(d => d.StudentName);


            foreach (var cn in captureNotes)
            {
                captureNoteModels.Add(new CaptureNoteModel()
                {
                    CapturedDate = cn.CapturedDate,
                    Email = cn.Email,
                    Id = cn.Id,
                    NoteLink = cn.NoteLink,
                    StudentName = cn.StudentName
                });
            }

            return View(captureNoteModels);
        }

        // Get a specified event.
        public ActionResult Details(int? id)
        {
            var facultyMail = Session["facultyMail"].ToString();
            CaptureNoteModel captureNoteModels = new CaptureNoteModel();

            var cn = db.captureNotes
                .Where(o => o.Id == id)
                .OrderBy(d => d.StudentName).FirstOrDefault();

            captureNoteModels = new CaptureNoteModel()
            {
                CapturedDate = cn.CapturedDate,
                Email = cn.Email,
                Id = cn.Id,
                NoteLink = cn.NoteLink,
                StudentName = cn.StudentName
            };


            return View(captureNoteModels);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int? id)
        {
            CaptureNoteModel captureNoteModels = new CaptureNoteModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }           

            var cn = db.captureNotes
                .Where(o => o.Id == id)
                .OrderBy(d => d.StudentName).FirstOrDefault();

            if (cn == null)
            {
                return HttpNotFound();
            }

            captureNoteModels = new CaptureNoteModel()
            {
                CapturedDate = cn.CapturedDate,
                Email = cn.Email,
                Id = cn.Id,
                NoteLink = cn.NoteLink,
                StudentName = cn.StudentName
            };
            
            
            return View(captureNoteModels);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var capture = db.captureNotes.Find(id);
            db.captureNotes.Remove(capture);
            db.SaveChanges();
            return RedirectToAction("Index").Success("Note Deleted");
        }
    }
}

WebApp/Controllers/FacultiesController.cs
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class FacultiesController : Controller
    {
        private OfficeHoursContext db = new OfficeHoursContext();

        
        // GET: Faculties/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Email,Id,first_Name,last_Name")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                if(db.faculties.Find(faculty.Email) != null)
                {
                    return RedirectToAction("Index", "Home").Error("Faculty already present.");
                }

                db.faculties.Add(faculty);
                db.SaveChanges();
                return RedirectToAction("Index", "Events").Success("Faculty Created");
            }
            return RedirectToAction("Index", "Events").Success("Faculty Created");
        }
        
    }
}

WebApp/Controllers/FacultyStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.DAL;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class FacultyStatusController : Controller
    {
        private OfficeHoursContext db = new OfficeHoursContext();
        // GET: FacultyStatus
        [HttpGet]
        public ActionResult SelectStatus()
        {
            List<string> flstatl = db.facultyStatuses.Select(s => s.Status).ToList();
            SelectList statusList = new SelectList(flstatl);
            ViewBag.StaList = statusList;
            return View();
        }

        [HttpPost]
        public ActionResult SelectStatus(String Status)
        {
            String stat = Request.Form["statusList"];
            if (Session["facultymail"] != null && stat != "Select a status")
            {
                Faculty fac = db.faculties.Find(Session["facultymail"]);
                if (fac != null)
                {
                    fac.Status = stat;
                    db.SaveChanges();
                }
            }
            else
            {
                return RedirectToAction("SelectStatus").Error("Select any Status from dropdown");
            }
            return RedirectToAction("Schedule","Home");
        }

        [HttpPost]
        public ActionResult CreateNew()
        {
            String newStat = Request.Form["newStatus"];
            if (Session["facultymail"] != null && newStat != "")
            {
                FacultyStatus facultyStatuses = db.facultyStatuses.Find(newStat);
                if (facultyStatuses == null)
                {
                    FacultyStatus newStatus = new FacultyStatus();
                    newStatus.Status = newStat;
                    db.facultyStatuses.Add(newStatus);
                    db.SaveChanges();
                    if (Session["facultymail"] != null)
                    {
                        Faculty fac = db.faculties.Find(Session["facultymail"]);
                        if (fac != null)
                        {
                            fac.Status = newStat;
                            db.SaveChanges();
                        }
                    }
                    return RedirectToAction("Schedule", "Home");
                }
              
            }
                return RedirectToAction("SelectStatus").Error("Incorrect status Message");
        }
    }
}

WebApp/Controllers/PhotoController.cs
using Microsoft.Graph;
using Resources;
using System;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApp.Helpers;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        FilesService filesService = new FilesService();
        EventsService eventsService = new EventsService();
        private OfficeHoursContext db = new OfficeHoursContext();

        [HttpGet]
        public ActionResult Index()
        {
            if (Session["facultyMail"] != null)
            {
                Session["val"] = "";
                return View();
            }
            return RedirectToAction("Home", "Home");
        }

        
        public async Task<ActionResult> SavePhoto()
        {
            byte[] byteArray;
            if (Session["dump"] == null)
            {
                return RedirectToAction("Index", "Error", new { message = string.Format("Try capturing the image again") });
            }
            byteArray = String_To_Bytes2(Session["dump"].ToString());
            // Initialize the GraphServiceClient.
            GraphServiceClient graphClient = SDKHelper.GetAuthenticatedClient();
            var userDetails = await eventsService.GetMyDetails(graphClient);
            var result = await filesService.CreateFile(graphClient, byteArray);
            try
            {
                CaptureNote captureNote = new CaptureNote()
                {
                    CapturedDate = DateTime.Now,
                    Email = Session["facultyMail"] != null ? Session["facultyMail"].ToString() : "",
                    NoteLink = result.Display,
                    StudentName = userDetails.DisplayName,                    
                };

                try
                {
                    db.captureNotes.Add(captureNote);
                    var val = db.SaveChanges();
                    if(val != 0)
                    {
                        var path = Server.MapPath("~/WebImages/");
                        System.IO.DirectoryInfo di = new DirectoryInfo(path);

                        foreach (FileInfo file in di.GetFiles())
                        {
                            file.Delete();
                        }
                    }
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.)
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            catch (ServiceException se)
            {
                if (se.Error.Message == Resource.Error_AuthChallengeNeeded) return new EmptyResult();

                // Personal accounts that aren't enabled for the Outlook REST API get a "MailboxNotEnabledForRESTAPI" or "MailboxNotSupportedForRESTAPI" error.
                return RedirectToAction("Index", "Error", new { message = string.Format(Resource.Error_Message, Request.RawUrl, se.Error.Code, se.Error.Message) });
            }

            return RedirectToAction("Index", "Student").Success("Note captured successfully.");
        }

        [HttpGet]
        public ActionResult Changephoto()
        {
            if (Convert.ToString(Session["val"]) != string.Empty)
            {
                ViewBag.pic = "http://localhost:4279/WebImages/" + Session["val"].ToString();
            }
            else
            {
                ViewBag.pic = "../../WebImages/person.jpg";
            }
            return View();
        }
               
        public JsonResult Rebind()
        {
            string path = "http://localhost:4279/WebImages/" + Session["val"].ToString();

            return Json(path, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Capture()
        {
            var stream = Request.InputStream;
            string dump;

            using (var reader = new StreamReader(stream))
            {
                dump = reader.ReadToEnd();

                DateTime nm = DateTime.Now;

                string date = nm.ToString("yyyymmddMMss");

                var path = Server.MapPath("~/WebImages/" + date + "test.jpg");

                System.IO.File.WriteAllBytes(path, String_To_Bytes2(dump));

                Session["dump"] = dump;

                ViewData["path"] = date + "test.jpg";

                Session["val"] = date + "test.jpg";
            }

            return View("Index");
        }

        private byte[] String_To_Bytes2(string strInput)
        {
            int numBytes = (strInput.Length) / 2;
            byte[] bytes = new byte[numBytes];

            for (int x = 0; x < numBytes; ++x)
            {
                bytes[x] = Convert.ToByte(strInput.Substring(x * 2, 2), 16);
            }

            return bytes;
        }        
    }
}

WebApp/Views/Shared/AllStatuses.cshtml
@using (Html.BeginForm("SelectStatus", "FacultyStatus", FormMethod.Post)) { 
    @Html.DropDownList("statusList", ViewBag.StaList as SelectList, "Select a status")
<input type="submit" />
}

WebApp/Views/Shared/FacultyStatus.cshtml
@model WebApp.Models.Faculty

<h3>Status: </h3> <h5> @Model.Status </h5>

WebApp/Views/Shared/_Flash.cshtml
<div id="flash-messages" class="alert" role="alert" style="display:none;">
    <a class="close" href="#">&times;</a>
    <p></p>
</div>


<script type="text/javascript">
    $(function () {
        $("#flash-messages").flashMessage();
    });

    $(document).ajaxComplete(function () {
        $("#flash-messages").flashMessage();
    });
</script>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Office Hours Application</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/fullcalendar.print.min.css" rel="stylesheet" media="print" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/fullcalendar.js"></script>
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
        <div class="container">
            <a class="navbar-brand float-left" href="#">@Html.ActionLink("OfficeHours", "Index", "Home", null, new { @class = "navbar-brand" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Home", "Home", null, new { @class = "nav-link" })</li>
                    @if (Request.IsAuthenticated && (Session["Role"] != null && Session["Role"].ToString().Equals("Faculty")))
                    {
                        <text>
                            @*<li class="nav-item">@Html.ActionLink("Read Mail", "ReadMail", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Send Mail", "SendMail", "Home", null, new { @class = "nav-link" })</li>*@
                            <li class="nav-item">@Html.ActionLink("Events", "Index", "Events", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("ViewNote", "Index", "Capture", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Messages", "Index", "FacultyMessages", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("UpdateStatus", "SelectStatus", "FacultyStatus", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("EnrollFaculty", "Create", "Faculties", null, new { @class = "nav-link" })</li>
                        </text>
                    }
                    @if (Request.IsAuthenticated && (Session["Role"] != null && Session["Role"].ToString().Equals("Student")))
                    {
                        <text>
                            <li class="nav-item">@Html.ActionLink("StudentAppointment", "Index", "Student", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("CaptureNote", "Index", "Photo", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Message", "Index", "StudentMessages", null, new { @class = "nav-link" })</li>
                        </text>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <div class="container body-content">
        @Html.Partial("_Flash")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OfficeHours Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery.cookie")
    @Scripts.Render("~/bundles/jquery.flashmessage")
    @Scripts.Render("~/bundles/jquery.timepicker")
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav a[href="' + url + '"]').parent().addClass('active');
            $('ul.nav a').filter(function () {
                return this.href == url;
            }).parent().addClass('active');
        });
        $('.timepicker').timepicker({
            timeFormat: 'hh:mm p',
            interval: 15,
            minTime: '8',
            maxTime: '5:00pm',
            defaultTime: '08',
            startTime: '08:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });
    </script>
</body>
</html>